### ISSUE TITLE
Integrate travis 

### ISSUE THREAD

**Issue by charithsoori** [99xt/github-manager-cli#15]
Travis supports CD capability.

http://docs.travis-ci.com/user/deployment/npm/

Instead of forgetting to publish manually, this should be enabled. Here's our GitFlow workflow:

Development occurs in the develop branch.
New Pull Requests must be to to be merged against this branch. However, Pull Requests will only be reviewed If the pull request can be merged and the tests passes. Also, the milestone must be set to the associated Issue.
After a new release has been planned, all the merged pull requests can be released.
On a new release, Tagging is added, the version is bumped in package.json and the Develop branch will be merged to Master, triggering the npm publish on Travis.

**Comment by winniehell** [comment]
@charithsoori It looks like this is solved. Could you close it or remove the hacktoberfest label?

**Comment by rajikaimal** [comment]
Done.
