### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by rajikaimal** [99xt/github-manager-cli#20]
Implement unit tests with [mocha](mochajs.org), probably with [chai](chaijs.com).

**Comment by G07cha** [comment]
Do not mind if I'll do that? Also, I was thinking about using [istanbul](https://github.com/gotwarlost/istanbul) for code coverage analysis.

**Comment by charithsoori** [comment]
That's nice.
About coverage we would like to see the data in codacy . Will we be able to config istanbul for it ?
https://www.codacy.com/app/99xt/github-manager-cli/dashboard

**Comment by G07cha** [comment]
@charithsoori, yeah it's also possible I'm planning to use [codacy-coverage](https://www.npmjs.com/package/codacy-coverage) package for this purposes. Let me know what do you think about this.

**Comment by charithsoori** [comment]
Package seems promising . Lets go ahead

**Comment by G07cha** [comment]
@charithsoori, @rajikaimal, please take a look at my pull request when you will have time. I've also sent you an email with test account credentials.

**Comment by rajikaimal** [comment]
I did a review #30

**Comment by rajikaimal** [comment]
@G07cha Nice work !
