### ISSUE TITLE
Undo pull request #40

### ISSUE THREAD

**Issue by charithsoori** [99xt/github-manager-cli#45]
Rever pull request and commit it to branch dev .
https://github.com/99xt/github-manager-cli/tree/dev

**Comment by charithsoori** [comment]
@rajikaimal I have reverted pull request and committed to branch dev. Could do you review it

**Comment by rajikaimal** [comment]
Sure, #44

**Comment by rajikaimal** [comment]
I will rename the title PR #40 since this problem arose with this particular PR.

**Comment by charithsoori** [comment]
Did it fix the problem.

**Comment by rajikaimal** [comment]
Seems like the intended code is still not here.

**Comment by rajikaimal** [comment]
Solves with [commit](https://github.com/99xt/github-manager-cli/commit/357180c0cabce4bcd12281be3dccf4750cc2fb50).

**Comment by charithsoori** [comment]
👍
