### ISSUE TITLE
ghm as an alias

### ISSUE THREAD

**Issue by rehrumesh** [99xt/github-manager-cli#55]
`gh-manager` is bit long for a terminal command and I believe a command such as `ghm` or similar short alias would be nice to have. To have the backward capability, we still could have `gh-manager` as the main command. Open for discussions.
@charithsoori  @rajikaimal

**Comment by BrainMaestro** [comment]
Can I pick this up?

**Comment by charithsoori** [comment]
I agree with you @rehrumesh  . @BrainMaestro  Please go ahead .
